Create create-jira-ticket-on-issue.yml
faunadb/faunadb-csharp pull request #141
Opened 2021-04-21 12:44 UTC by fireridlle

2021-04-21 13:23 UTC, parkhomenko approved these changes, later dismissed

2021-05-06 14:41 UTC, evbruno approved these changes, later dismissed

2021-07-26 21:31 UTC, macnealefauna requested changes, later dismissed

2021-07-26 21:31 UTC, macnealefauna commented on .github/workflows/create-jira-ticket-on-issue.yml
> +            echo "::set-output name=DESC::${{github.event.issue.url}} \n\n ${{github.event.issue.body}}"
github.event.issue.html_url

2021-07-26 21:31 UTC, macnealefauna commented on .github/workflows/create-jira-ticket-on-issue.yml
> +        uses: atlassian/gajira-create@master
s/master/main/

2021-07-26 21:31 UTC, macnealefauna commented on .github/workflows/create-jira-ticket-on-issue.yml
> +        uses: atlassian/gajira-transition@master
s/master/main/

2022-02-11 01:35 UTC, cleve-fauna commented on .github/workflows/create-jira-ticket-on-issue.yml
> +        uses: atlassian/gajira-transition@master
actually needs to be master

2022-02-11 01:37 UTC, cleve-fauna commented on .github/workflows/create-jira-ticket-on-issue.yml
> +            echo "::set-output name=DESC::${{github.event.issue.url}} \n\n ${{github.event.issue.body}}"
```suggestion
            echo "::set-output name=DESC::${{github.event.issue.html_url}} \n\n ${{github.event.issue.body}}"
```

2022-02-11 01:38 UTC, cleve-fauna approved these changes

2022-02-11 01:38 UTC, merged